# Generated by Django 5.2.8 on 2025-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('Portada', models.URLField(max_length=500)),
                ('Autor', models.CharField(max_length=200)),
                ('Paginas', models.PositiveIntegerField()),
            ],
        ),
    ]
