# Generated by Django 5.2.8 on 2025-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Fecha',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
