# Generated by Django 5.2.8 on 2025-11-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libro_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Portada',
        ),
    ]
