# Generated by Django 5.2.8 on 2025-12-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_libro_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='libro',
            name='Año',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='libro',
            name='Categoria',
            field=models.TextField(default=None),
        ),
    ]
