# Generated by Django 5.2.8 on 2025-12-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_libro_fecha_libro_año_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Categoria',
            field=models.TextField(),
        ),
    ]
