# Generated by Django 5.2.8 on 2025-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_libro_año_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Categoria',
            field=models.TextField(max_length=200),
        ),
    ]
