# Generated by Django 5.2.8 on 2025-12-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Año',
            field=models.PositiveIntegerField(),
        ),
    ]
