# Generated by Django 5.2.8 on 2025-11-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_libro_portada'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_libro',
        ),
        migrations.AddField(
            model_name='perfil',
            name='favorito',
            field=models.ManyToManyField(blank=True, to='api.libro'),
        ),
    ]
