# Generated by Django 5.2.8 on 2025-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perfil_id_libro_perfil_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='favorito',
            new_name='favoritos',
        ),
    ]
